### ISSUE TITLE
Add CRUD functionality to blogs

### ISSUE THREAD

**Issue by reyesjl** [reyesjl/f5#40]
## Description
- As a user I want to be able to read an article 
- As admin I want to be able to browse all articles on the blog home page
- As admin I want to be able create, update, and delete an article

## Tasks
- [x] create routes for detail, update, and delete
- [x] create templates for detail update and delete
- [x] create style for richtext
- [x] create js for richtext images
