### ISSUE TITLE
Create player profiles / user accounts

### ISSUE THREAD

**Issue by reyesjl** [reyesjl/f5#45]
## Description
- As a new visitor to the site I want to be able to register as a user. 
- As a User I want to be able to view my dashboard.
- As an Admin I want to be able to change user account types.
- As a player user, stats profiles are available and displayed on that users dashboard. 
- As a health manager, I can view and modify player stats. 

## Tasks
- [x] create members app
- [x] make login routes, and urls
- [x] make authorization views login, signup, dashboard
- [x] make authorization templates login, signup, dashboard
- [x] create all authorization forms

**Comment by reyesjl** [comment]
done.
